---
sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'

env:
  PYTHONPATH: .:resources/lib
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

before_script:
  - cd $HOME

script:
- tox
- tox -e flake8
- pylint resources/lib/
# - kodi-addon-checker $TRAVIS_BUILD_DIR --branch=krypton
