language: python
python:
  - "3.7"

install:
  - pip install kodi-addon-checker
  - pip install requests-cache

before_script:
  - cd $HOME

script:
  - kodi-addon-checker $TRAVIS_BUILD_DIR --branch=jarvis
