---
sudo: false
language: python
python:
- '3.7'

env:
  PYTHONPATH: .:resources/lib
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

before_script:
  - cd $HOME

script:
- kodi-addon-checker $TRAVIS_BUILD_DIR --branch=krypton
